#!/usr/bin/env zsh

CONTAINERCMD="${CONTAINERCMD:-podman}"
CONTAINERURI="${CONTAINERURI:-ghcr.io/antznin/bitbake-setup:latest}"

declare -a args=(
  --rm
  --interactive
  --tty
  --device /dev/kvm
  --device /dev/net/tun
  --device /dev/vhost-net
)

if [ "$CONTAINERCMD" = "podman" ]; then
  args+=(
    --userns=keep-id:uid="$(id -u)",gid="$(id -g)"
    --security-opt seccomp=unconfined
    --security-opt label=disable
    --cap-add=NET_ADMIN
    --cap-add=NET_RAW
    --pids-limit=0
  )
elif [ "$CONTAINERCMD" != "docker" ]; then
  echo "CONTAINERCMD unknown: $CONTAINERCMD"
  exit 1
fi

$CONTAINERCMD run \
  "${args[@]}" \
  "$@" \
  "$CONTAINERURI"
